In [38]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [39]:
df = pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv').drop(columns=['store room','floor_category','balcony'])

In [40]:
df.head()

,price,sector,bedRoom,bathroom,agePossession,property_type,built_up_area,servant room,furnishing_type,luxury_category
0,15.50,sector 43,5,6,Moderately Old,house,5490.00,1,0,Medium
1,0.38,sohna road,2,2,Relatively New,flat,602.00,0,0,Low
2,0.70,sector 92,3,2,Relatively New,flat,1325.00,0,0,Medium
3,1.60,sector 102,3,3,Relatively New,flat,1315.00,0,0,Low
4,3.98,sector 66,3,4,Moderately Old,flat,2200.11,1,2,Medium

# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished

# Numerical = bedRoom, bathroom, built_up_area, servant room
# Ordinal = property_type, furnishing_type, luxury_category 
# OHE = sector, agePossession

In [41]:
df['agePossession'] = df['agePossession'].replace(
    {
        'Relatively New':'new',
        'Moderately Old':'old',
        'New Property' : 'new',
        'Old Property' : 'old',
        'Under Construction' : 'under construction'
    }
)

In [42]:
df.head()

,price,sector,bedRoom,bathroom,agePossession,property_type,built_up_area,servant room,furnishing_type,luxury_category
0,15.50,sector 43,5,6,old,house,5490.00,1,0,Medium
1,0.38,sohna road,2,2,new,flat,602.00,0,0,Low
2,0.70,sector 92,3,2,new,flat,1325.00,0,0,Medium
3,1.60,sector 102,3,3,new,flat,1315.00,0,0,Low
4,3.98,sector 66,3,4,old,flat,2200.11,1,2,Medium

In [43]:
df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_17020\71934247.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

In [44]:
df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

C:\Users\Rahul Kuniyal\AppData\Local\Temp\ipykernel_17020\2576796079.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

In [45]:
df.head()

,price,sector,bedRoom,bathroom,agePossession,property_type,built_up_area,servant room,furnishing_type,luxury_category
0,15.50,sector 43,5,6,old,1,5490.00,1,0,1
1,0.38,sohna road,2,2,new,0,602.00,0,0,0
2,0.70,sector 92,3,2,new,0,1325.00,0,0,1
3,1.60,sector 102,3,3,new,0,1315.00,0,0,0
4,3.98,sector 66,3,4,old,0,2200.11,1,2,1

In [46]:
new_df = pd.get_dummies(df,columns=['sector','agePossession'],drop_first=True)

In [47]:
X = new_df.drop(columns=['price'])
y = new_df['price']

In [48]:
y_log = np.log1p(y)

In [49]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [50]:
X_scaled = pd.DataFrame(X_scaled,columns=X.columns)

In [51]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(LinearRegression(), X_scaled, y_log, cv=kfold, scoring='r2')

In [52]:
scores.mean(),scores.std()

(np.float64(0.8529991965665777), np.float64(0.016203449949199582))

In [53]:
lr = LinearRegression()
ridge = Ridge(alpha=0.0001)

In [54]:
lr.fit(X_scaled,y_log)

LinearRegression()

In [55]:
lr.fit(X_scaled, y_log)

LinearRegression()

In [56]:
lr.coef_

array([ 5.38787345e-02,  6.58344085e-02,  1.22317717e-01,  2.08691028e-01,
        5.04008231e-02,  7.18452447e-03,  5.42499340e-03,  1.01346919e-02,
       -2.23958994e-02, -3.09758072e-03, -3.84603731e-03, -5.01870699e-03,
        2.76896011e-02, -2.92966404e-03,  2.51676365e-03, -1.96591001e-02,
        9.60006583e-04, -1.25156111e-02,  1.73821827e-02,  2.64353728e-02,
        5.23534903e-03, -1.51606002e-02,  1.29348561e-02,  1.65822206e-02,
        3.12639283e-02,  3.27497667e-02, -1.95360730e-02, -1.24672805e-02,
        2.88084058e-02,  3.25741334e-03,  6.75277779e-03,  3.82285021e-03,
        1.33869543e-02,  6.78657562e-03, -9.50105683e-03,  3.64375487e-02,
        2.03693978e-03,  1.78731011e-02,  5.76214293e-02,  7.40774760e-02,
        6.93169529e-03,  4.20186600e-02, -1.28981437e-02, -1.08981300e-02,
       -1.42812449e-02,  6.46221597e-03,  2.24628067e-02,  2.62028298e-02,
       -6.97784836e-03,  1.08349693e-02, -2.42820864e-03, -1.10726448e-02,
        1.46939376e-03,  1.20713276e-02,  2.99705698e-03, -2.11591261e-02,
        7.49045075e-03,  1.69002088e-02,  6.07094175e-02,  2.71585755e-02,
        1.55549039e-02,  1.28764014e-02,  5.45240304e-02,  3.20345067e-02,
       -3.24553727e-03,  7.21071487e-02,  3.00468559e-04,  5.02824840e-03,
        4.79804143e-02,  4.62090779e-02,  1.25357308e-02,  1.20674305e-02,
        2.52351406e-02,  2.37269537e-02,  3.19556792e-02, -1.59549991e-02,
        2.42014774e-02,  3.68250570e-02,  4.11180247e-02,  3.50813600e-02,
        2.35448816e-02,  7.19444679e-02,  5.33341725e-02,  4.13558023e-02,
        8.85101363e-03,  1.09866594e-02,  1.90597692e-02, -7.63210102e-03,
        5.96216064e-03,  1.76166253e-02, -3.02876481e-03,  3.07223887e-02,
       -1.10655021e-03,  2.24672314e-02, -9.95796875e-05,  1.13801509e-03,
       -4.06057586e-03,  1.37521872e-02, -1.36869476e-02,  3.22665415e-04,
        1.73038231e-02,  9.72251498e-04,  1.06892626e-02, -5.08120161e-04,
       -9.77923122e-03,  9.45406483e-03, -3.15053616e-03,  9.02551034e-03,
        1.58900254e-05,  2.28300697e-03, -1.36634772e-02, -1.13451702e-02,
        3.72271812e-04, -2.77869229e-02, -3.88418768e-03, -2.46420702e-02,
        1.56824967e-03, -1.28015334e-02, -5.03689700e-03, -2.74573200e-02,
       -9.41052478e-03, -7.01170820e-03,  1.64246592e-02])

In [57]:
ridge = Ridge(alpha=0.0001)

In [58]:
ridge.fit(X_scaled, y_log)

Ridge(alpha=0.0001)

In [62]:
coef_df = pd.DataFrame(ridge.coef_.reshape(1,123),columns=X_scaled.columns).stack().reset_index().drop(columns = ['level_0']).rename(columns = {'level_1' :'feature', 0 : 'coef' })

In [63]:
coef_df

                              feature      coef
0                             bedRoom  0.053879
1                            bathroom  0.065834
2                       property_type  0.122318
3                       built_up_area  0.208691
4                        servant room  0.050401
..                                ...       ...
118                  sector_sector 9a -0.005037
119                 sector_sohna road -0.027458
120            sector_sohna road road -0.009411
121                 agePossession_old -0.007012
122  agePossession_under construction  0.016425

[123 rows x 2 columns]

In [64]:
# 1. Import necessary libraries
import statsmodels.api as sm

# 2. Add a constant to X
X_with_const = sm.add_constant(X_scaled)

# 3. Fit the model
model = sm.OLS(y_log, X_with_const).fit()

# 4. Obtain summary statistics
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.866
Model:                            OLS   Adj. R-squared:                  0.861
Method:                 Least Squares   F-statistic:                     179.5
Date:                Wed, 08 Jul 2026   Prob (F-statistic):               0.00
Time:                        19:36:50   Log-Likelihood:                 597.38
No. Observations:                3554   AIC:                            -946.8
Df Residuals:                    3430   BIC:                            -181.0
Df Model:                         123
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
const                                 1.0461      0.003    299.554      0.000       1.039       1.053
bedRoom                               0.0539      0.007      8.154      0.000       0.041       0.067
bathroom                              0.0658      0.007      9.603      0.000       0.052       0.079
property_type                         0.1223      0.005     22.882      0.000       0.112       0.133
built_up_area                         0.2087      0.005     41.216      0.000       0.199       0.219
servant room                          0.0504      0.005     11.107      0.000       0.042       0.059
furnishing_type                       0.0072      0.004      1.786      0.074      -0.001       0.015
luxury_category                       0.0054      0.004      1.341      0.180      -0.003       0.013
sector_gwal pahari                    0.0101      0.006      1.602      0.109      -0.002       0.023
sector_manesar                       -0.0224      0.008     -2.883      0.004      -0.038      -0.007
sector_new                           -0.0031      0.004     -0.724      0.469      -0.011       0.005
sector_new sector 2                  -0.0038      0.004     -0.860      0.390      -0.013       0.005
sector_sector 1                      -0.0050      0.005     -1.080      0.280      -0.014       0.004
sector_sector 102                     0.0277      0.013      2.103      0.035       0.002       0.053
sector_sector 103                    -0.0029      0.009     -0.339      0.735      -0.020       0.014
sector_sector 104                     0.0025      0.011      0.236      0.814      -0.018       0.023
sector_sector 105                    -0.0197      0.007     -2.968      0.003      -0.033      -0.007
sector_sector 106                     0.0010      0.008      0.114      0.909      -0.016       0.017
sector_sector 107                    -0.0125      0.010     -1.237      0.216      -0.032       0.007
sector_sector 108                     0.0174      0.010      1.732      0.083      -0.002       0.037
sector_sector 109                     0.0264      0.012      2.220      0.027       0.003       0.050
sector_sector 10a                     0.0052      0.005      1.088      0.277      -0.004       0.015
sector_sector 11                     -0.0152      0.006     -2.476      0.013      -0.027      -0.003
sector_sector 110                     0.0129      0.007      1.903      0.057      -0.000       0.026
sector_sector 111                     0.0166      0.007      2.446      0.014       0.003       0.030
sector_sector 112                     0.0313      0.007      4.510      0.000       0.018       0.045
sector_sector 113                     0.0327      0.009      3.713      0.000       0.015       0.050
sector_sector 12                     -0.0195      0.008     -2.481      0.013      -0.035      -0.004
sector_sector 13                     -0.0125      0.005     -2.415      0.016      -0.023      -0.002
sector_sector 14                      0.0288      0.006      4.519      0.000       0.016       0.041
sector_sector 15                      0.0033      0.005      0.700      0.484      -0.006       0.012
sector_sector 17                      0.0068      0.005      1.448      0.148      -0.002       0.016
sector_sector 17a                     0.0038      0.004      1.028      0.304      -0.003       0.011
sector_sector 17b                     0.0134      0.004      3.239      0.001       0.005       0.021
sector_sector 2                       0.0068      0.010      0.658      0.511      -0.013       0.027
sector_sector 21                     -0.0095      0.005     -2.042      0.041      -0.019      -0.000
sector_sector 22                      0.0364      0.007      5.559      0.000       0.024       0.049
sector_sector 23                      0.0020      0.006      0.355      0.722      -0.009       0.013
sector_sector 24                      0.0179      0.007      2.708      0.007       0.005       0.031
sector_sector 25                      0.0576      0.008      6.855      0.000       0.041       0.074
sector_sector 26                      0.0741      0.009      8.522      0.000       0.057       0.091
sector_sector 27                      0.0069      0.004      1.763      0.078      -0.001       0.015
sector_sector 28                      0.0420      0.009      4.931      0.000       0.025       0.059
sector_sector 3                      -0.0129      0.007     -1.831      0.067      -0.027       0.001
sector_sector 3 phase 2              -0.0109      0.005     -2.349      0.019      -0.020      -0.002
sector_sector 3 phase 3 extension    -0.0143      0.005     -2.778      0.006      -0.024      -0.004
sector_sector 30                      0.0065      0.004      1.441      0.150      -0.002       0.015
sector_sector 31                      0.0225      0.005      4.241      0.000       0.012       0.033
sector_sector 33                      0.0262      0.011      2.468      0.014       0.005       0.047
sector_sector 36                     -0.0070      0.005     -1.292      0.196      -0.018       0.004
sector_sector 36a                     0.0108      0.005      2.004      0.045       0.000       0.021
sector_sector 37                     -0.0024      0.004     -0.654      0.513      -0.010       0.005
sector_sector 37c                    -0.0111      0.009     -1.170      0.242      -0.030       0.007
sector_sector 37d                     0.0015      0.010      0.142      0.887      -0.019       0.022
sector_sector 38                      0.0121      0.005      2.280      0.023       0.002       0.022
sector_sector 39                      0.0030      0.005      0.553      0.581      -0.008       0.014
sector_sector 4                      -0.0212      0.009     -2.330      0.020      -0.039      -0.003
sector_sector 40                      0.0075      0.004      1.666      0.096      -0.001       0.016
sector_sector 41                      0.0169      0.005      3.098      0.002       0.006       0.028
sector_sector 43                      0.0607      0.010      6.018      0.000       0.041       0.080
sector_sector 45                      0.0272      0.005      5.444      0.000       0.017       0.037
sector_sector 46                      0.0156      0.005      2.841      0.005       0.005       0.026
sector_sector 47                      0.0129      0.006      2.110      0.035       0.001       0.025
sector_sector 48                      0.0545      0.010      5.516      0.000       0.035       0.074
sector_sector 49                      0.0320      0.009      3.545      0.000       0.014       0.050
sector_sector 5                      -0.0032      0.005     -0.697      0.486      -0.012       0.006
sector_sector 50                      0.0721      0.010      6.953      0.000       0.052       0.092
sector_sector 51                      0.0003      0.005      0.063      0.950      -0.009       0.010
sector_sector 52                      0.0050      0.006      0.862      0.389      -0.006       0.016
sector_sector 53                      0.0480      0.006      8.267      0.000       0.037       0.059
sector_sector 54                      0.0462      0.007      6.361      0.000       0.032       0.060
sector_sector 55                      0.0125      0.005      2.368      0.018       0.002       0.023
sector_sector 56                      0.0121      0.010      1.243      0.214      -0.007       0.031
sector_sector 57                      0.0252      0.007      3.619      0.000       0.012       0.039
sector_sector 58                      0.0237      0.005      4.935      0.000       0.014       0.033
sector_sector 59                      0.0320      0.005      6.464      0.000       0.022       0.042
sector_sector 6                      -0.0160      0.005     -2.932      0.003      -0.027      -0.005
sector_sector 60                      0.0242      0.006      4.054      0.000       0.012       0.036
sector_sector 61                      0.0368      0.009      4.278      0.000       0.020       0.054
sector_sector 62                      0.0411      0.006      6.903      0.000       0.029       0.053
sector_sector 63                      0.0351      0.006      6.032      0.000       0.024       0.046
sector_sector 63a                     0.0235      0.006      3.977      0.000       0.012       0.035
sector_sector 65                      0.0719      0.012      6.006      0.000       0.048       0.095
sector_sector 66                      0.0533      0.009      6.133      0.000       0.036       0.070
sector_sector 67                      0.0414      0.009      4.492      0.000       0.023       0.059
sector_sector 67a                     0.0089      0.007      1.327      0.185      -0.004       0.022
sector_sector 68                      0.0110      0.008      1.461      0.144      -0.004       0.026
sector_sector 69                      0.0191      0.012      1.540      0.124      -0.005       0.043
sector_sector 7                      -0.0076      0.008     -0.930      0.352      -0.024       0.008
sector_sector 70                      0.0060      0.009      0.640      0.522      -0.012       0.024
sector_sector 70a                     0.0176      0.010      1.808      0.071      -0.001       0.037
sector_sector 71                     -0.0030      0.007     -0.412      0.680      -0.017       0.011
sector_sector 72                      0.0307      0.008      4.060      0.000       0.016       0.046
sector_sector 73                     -0.0011      0.004     -0.270      0.787      -0.009       0.007
sector_sector 74                      0.0225      0.006      3.545      0.000       0.010       0.035
sector_sector 76                  -9.958e-05      0.006     -0.018      0.986      -0.011       0.011
sector_sector 77                      0.0011      0.007      0.155      0.877      -0.013       0.016
sector_sector 78                     -0.0041      0.006     -0.668      0.504      -0.016       0.008
sector_sector 79                      0.0138      0.011      1.218      0.223      -0.008       0.036
sector_sector 8                      -0.0137      0.005     -2.830      0.005      -0.023      -0.004
sector_sector 80                      0.0003      0.004      0.072      0.943      -0.008       0.009
sector_sector 81                      0.0173      0.012      1.442      0.149      -0.006       0.041
sector_sector 82                      0.0010      0.009      0.112      0.911      -0.016       0.018
sector_sector 82a                     0.0107      0.006      1.659      0.097      -0.002       0.023
sector_sector 83                     -0.0005      0.011     -0.047      0.962      -0.022       0.021
sector_sector 84                     -0.0098      0.009     -1.047      0.295      -0.028       0.009
sector_sector 85                      0.0095      0.013      0.717      0.474      -0.016       0.035
sector_sector 86                     -0.0032      0.010     -0.305      0.760      -0.023       0.017
sector_sector 88a                     0.0090      0.007      1.329      0.184      -0.004       0.022
sector_sector 88b                  1.589e-05      0.004      0.004      0.997      -0.008       0.008
sector_sector 89                      0.0023      0.010      0.231      0.818      -0.017       0.022
sector_sector 9                      -0.0137      0.006     -2.442      0.015      -0.025      -0.003
sector_sector 90                     -0.0113      0.012     -0.941      0.347      -0.035       0.012
sector_sector 91                      0.0004      0.006      0.060      0.952      -0.012       0.013
sector_sector 92                     -0.0278      0.013     -2.182      0.029      -0.053      -0.003
sector_sector 93                     -0.0039      0.005     -0.760      0.447      -0.014       0.006
sector_sector 95                     -0.0246      0.010     -2.531      0.011      -0.044      -0.006
sector_sector 99                      0.0016      0.006      0.283      0.777      -0.009       0.012
sector_sector 99a                    -0.0128      0.008     -1.679      0.093      -0.028       0.002
sector_sector 9a                     -0.0050      0.005     -0.953      0.341      -0.015       0.005
sector_sohna road                    -0.0275      0.015     -1.781      0.075      -0.058       0.003
sector_sohna road road               -0.0094      0.005     -1.739      0.082      -0.020       0.001
agePossession_old                    -0.0070      0.005     -1.400      0.161      -0.017       0.003
agePossession_under construction      0.0164      0.004      4.050      0.000       0.008       0.024
==============================================================================
Omnibus:                      500.543   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4642.638
Skew:                          -0.355   Prob(JB):                         0.00
Kurtosis:                       8.554   Cond. No.                         40.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.